// src/Resume.js
import React from 'react';
import '../css/Resume.css';  // Para los estilos personalizados
import clarioLogo from '../images/clario.png';
import encoraLogo from '../images/encora.png';
import moptLogo from '../images/mopt.png';

function Resume() {
  return (
    <div>
      <section id="education" className="resume">
        <h2>Education</h2>
        <div className="education__item">
          <h3>Instituto Tecnológico de Costa Rica</h3>
          <p>Master’s Degree in Computer Science (2023 – Currently)</p>
        </div>
        <div className="education__item">
          <h3>Universidad Nacional de Costa Rica</h3>
          <p>Bachelor’s Degree in University (2016 – 2021)</p>
        </div>
        <div className="education__item">
          <h3>Diploma in Programming of Computer Applications</h3>
          <p>Diploma in Programming of Computer Applications (2016 – 2019)</p>
        </div>
      </section>

      <section id="work_experience" className="resume">
        <h2>Work Experience</h2>
        <div className="work_experience__item">
          <div className="work_experience__company">
            <img src={clarioLogo} alt="Clario Logo" className="company-logo" />
            <h3>Software Development Engineer</h3>
          </div>
          <p className="work_experience__dates">2022 – 2024 | Clario</p>
          <p>As a Developer Engineer at Clario, I worked in different projects, leveraging the internal API to deliver innovative solutions. Key responsibilities included contributing to multiple projects, enhancing features, ensuring timely delivery, and conducting unit testing to uphold code quality and robust functionality. I have collaborated with different teams, adapted to diverse client requirements, and managed multiple project timelines. For complex projects, I customized applications by writing custom JavaScript functions to satisfy specific client needs and deliver quality solutions.</p>
          <p><strong>Technologies:</strong> JavaScript, JSON, jQuery, CSS, HTML, and SQL.</p>
        </div>

        <div className="work_experience__item">
          <div className="work_experience__company">
            <img src={encoraLogo} alt="Encora Logo" className="company-logo" />
            <h3>QA Engineer</h3>
          </div>
          <p className="work_experience__dates">2021 – 2022 | Encora</p>
          <p>I participated in various Quality Assurance projects, working with the agile scrum methodology to ensure and certify the quality of these systems. Key responsibilities included test case estimation, specification, and execution. This included various aspects such as regression testing, UX/UI testing. Additionally, I provided support to expert users during test execution.</p>
          <p><strong>Technologies:</strong> Microsoft Test Manager (MTM), Microsoft TFS, Automation Anywhere and VMWare.</p>
        </div>

        <div className="work_experience__item">
          <div className="work_experience__company">
            <img src={moptLogo} alt="MOPT Logo" className="company-logo" />
            <h3>Software Developer Student</h3>
          </div>
          <p className="work_experience__dates">2019 – 2021 | MOPT</p>
          <p>During this time, I developed the HelpDesk system to manage incidents generated by users in the Information Technology Department of the Human Resources Unit, working with the agile scrum methodology. The system also incorporated best practices in UX/UI design for an enhanced user experience. I developed the statistics of the incidents using JavaScript, C#, Bootstrap, and JQuery to maintain the format of the window (PopUp) and obtain the necessary data to create the graphics.</p>
          <p><strong>Technologies:</strong> C#, ASP.NET MVC, Bootstrap, JQuery, SQL Server.</p>
        </div>
      </section>
    </div>
  );
}

export default Resume;
